apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookstore.fullname" . }}
  labels:
    {{- include "bookstore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "bookstore.name" . }}
